weak_ptr - changes due to code review
J-Cieplinski/memory-management pull request #14
Opened 2020-10-15 20:36 UTC by majkel84

2020-10-15 21:08 UTC, J-Cieplinski requested changes

2020-10-15 21:08 UTC, J-Cieplinski commented on homework/shared_ptr/weak_ptr.hpp
> +    void checkWeakAndDeletePointers();
remove that

2020-10-15 21:08 UTC, J-Cieplinski commented on homework/shared_ptr/weak_ptr.hpp
> +}
as well as this. It's basically duplicating `checkAndDeletePointers` and I want counter decrease to be explicitly called

2020-10-15 21:08 UTC, J-Cieplinski commented on homework/shared_ptr/weak_ptr.hpp
> +    checkWeakAndDeletePointers();
```suggestion
if(counter_) {
    counter_->decreaseWeakRefs();
    checkAndDeletePointers();
}
```

2020-10-15 21:08 UTC, J-Cieplinski commented on homework/shared_ptr/weak_ptr.hpp
> +    checkWeakAndDeletePointers();
```suggestion
if(counter_) {
    counter_->decreaseWeakRefs();
    checkAndDeletePointers();
}
```

2020-10-16 20:14 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +    checkWeakAndDeletePointers();
done

2020-10-16 20:14 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +    checkWeakAndDeletePointers();
done

2020-10-18 07:53 UTC, J-Cieplinski commented on homework/shared_ptr/weak_ptr.hpp
>      if (counter_) {
```suggestion
    if (this != &ptr) {
        if(counter_) {
            counter_->decreaseWeakRefs();
            checkAndDeletePointers();
        }
    ptr_ = ptr.ptr_;
    counter_ = ptr.counter_;
```

2020-10-18 19:05 UTC, J-Cieplinski approved these changes

2020-10-18 19:05 UTC, merged